### ISSUE TITLE
cannot find package

### ISSUE THREAD

**Issue by SigniOS** [mwpcheung/gsalogin#1]
mac@macdeMacBook-Pro src % go run *.go
gsanet.go:4:2: cannot find package "pphelp/plistlib" in any of:
	/usr/local/Cellar/go@1.14/1.14.10/libexec/src/pphelp/plistlib (from $GOROOT)
	/Users/mac/go/src/pphelp/plistlib (from $GOPATH)
gsanet.go:5:2: cannot find package "webv/net" in any of:
	/usr/local/Cellar/go@1.14/1.14.10/libexec/src/webv/net (from $GOROOT)
	/Users/mac/go/src/webv/net (from $GOPATH)

**Comment by mwpcheung** [comment]
some of them are private workspace, now is buildable

SigniOS <notifications@github.com> 于2020年11月5日周四 上午11:52写道：
