### ISSUE TITLE
2020/11/05 13:31:39 登陆失败 

### ISSUE THREAD

**Issue by SigniOS** [mwpcheung/gsalogin#2]
-29004 This action could not be completed due to possible environment mismatch.
2020/11/05 13:30:17 &{StatusCode:433 ErrorDescrption: ErrorCode:-29004 ErrorMessage:This action could not be completed due to possible environment mismatch.}

**Comment by mwpcheung** [comment]
This is not an issue

**Comment by SigniOS** [comment]
I would like to ask how to deal with it, he still prompted this problem

**Comment by SigniOS** [comment]
Do you have any other contact information? I want to know more about you
