### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by SigniOS** [mwpcheung/gsalogin#3]
2020/11/05 14:28:57 登陆失败 -29004 {%!s(int=433)  %!s(int=-29004) This action could not be completed due to possible environment mismatch.}
2020/11/05 14:28:57 &{StatusCode:433 ErrorDescrption: ErrorCode:-29004 ErrorMessage:This action could not be completed due to possible environment mismatch.}

**Comment by SigniOS** [comment]
账号密码填入后，校验M1后提示登录失败

**Comment by SigniOS** [comment]
-22421 This action could not be completed. Try again.
2020/11/05 14:40:31 &{StatusCode:434 ErrorDescrption: ErrorCode:-22421 ErrorMessage:This action could not be completed. Try again.}

**Comment by SigniOS** [comment]
![image](https://s1.ax1x.com/2020/11/05/BRp5GV.png)

**Comment by SigniOS** [comment]
多次换代理尝试都提示22421，换了香港代理美国代理依旧这样，坑请作者再次给以提示

**Comment by SigniOS** [comment]
Author, paid to help solve the problem, thank you for the source code, my contact QQ: 2471036677

**Comment by mwpcheung** [comment]
opt timeout
