### ISSUE TITLE
errorcode:-29004 in itunes 12.5.3.16 

### ISSUE THREAD

**Issue by KJY5713** [mwpcheung/gsalogin#6]
1. I entered the imd value within 30 seconds using frida, compiled it, and ran gsalogin.exe.
2. I installed itunes. The version is 12.5.3.16(64bit).
3. Fiddler was used for proxy.
4. I tested using both IDs, but both had the same error. Look down.
![image](https://user-images.githubusercontent.com/71558028/148738496-bdbfb8ee-4340-4501-8b73-b8f79adcce08.png)

How should I do? I want to test gsalogin!!
Please, Let me know in details.
@mwpcheung

**Comment by mwpcheung** [comment]
use iPhone jb device, iOS10

KJY5713 ***@***.***> 于2022年1月10日周一 16:50写道：
